#!/usr/bin/env python3
"""
Final Collaboration Demo

Demonstrates the complete collaboration pipeline with clean output.
"""

import asyncio
import sys
import os
import time

# Add the backend directory to the Python path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app.services.collaboration_engine import CollaborationEngine
from config import get_settings

async def demo_collaboration():
    """Demo the collaboration system"""
    
    settings = get_settings()
    
    # Get API keys
    api_keys = {}
    if settings.openai_api_key:
        api_keys["openai"] = settings.openai_api_key
    if settings.perplexity_api_key:
        api_keys["perplexity"] = settings.perplexity_api_key  
    if settings.google_api_key:
        api_keys["gemini"] = settings.google_api_key
        
    print("🧠 Syntra AI Collaboration System Demo")
    print("=" * 60)
    print(f"📊 Available Models: {len(api_keys)} providers")
    print("   • OpenAI: gpt-4o, gpt-4o-mini")
    print("   • Perplexity: sonar-pro")
    print("   • Gemini: gemini-2.5-flash")
    
    # Test query
    query = "What are the key considerations for implementing a microservices architecture?"
    
    print(f"\n🤔 Query: {query}")
    print("\n🚀 Starting 5-Agent Collaboration...")
    
    # Initialize collaboration engine
    engine = CollaborationEngine()
    
    try:
        start_time = time.perf_counter()
        
        # Run collaboration
        result = await engine.collaborate(
            user_query=query,
            turn_id="demo_2024",
            api_keys=api_keys,
            collaboration_mode=True
        )
        
        duration = time.perf_counter() - start_time
        
        print(f"✅ Collaboration completed in {duration:.1f}s")
        print(f"📊 {len(result.agent_outputs)} agents participated")
        
        # Show step-by-step process
        print("\n📋 Collaboration Steps:")
        for i, output in enumerate(result.agent_outputs):
            step = i + 1
            print(f"\n   Step {step}: {output.role.value.title()} ({output.provider})")
            preview = output.content[:120] + "..." if len(output.content) > 120 else output.content
            print(f"   💭 {preview}")
        
        # Display final result
        print("\n" + "="*80)
        print("🎯 FINAL COLLABORATION RESULT")
        print("="*80)
        print(f"\n📋 Question: {query}")
        print(f"\n💬 Collaborative AI Response:\n")
        print(result.final_report)
        print("\n" + "="*80)
        print("✨ Generated by 5-agent collaboration: Analyst → Researcher → Creator → Critic → Synthesizer")
        print("🤝 Each agent built upon the previous insights to create this comprehensive response")
        
        return True
        
    except Exception as e:
        print(f"❌ Collaboration failed: {e}")
        print("\n💡 Troubleshooting suggestions:")
        print("   1. Verify all API keys are valid and have quota")
        print("   2. Check network connectivity")
        print("   3. Review model availability")
        return False

if __name__ == "__main__":
    success = asyncio.run(demo_collaboration())
    
    if success:
        print("\n🎉 Collaboration system is fully operational!")
        print("   All 5 steps work correctly and produce high-quality results.")
    else:
        print("\n⚠️  Please check the configuration and try again.")